clc; clear all; close all;
x_dat = [0;1;2;5];
y_dat = [0;3;3;6];
m = length(x_dat);
A = [ones(m,1),x_dat];
b = y_dat;
M = A'*A;
N = A'*b;
c = inv(M)*N;
y_pred = A*c;   
residuals =y_dat-y_pred;
SE = sum(residuals.^2);  
RMSE = sqrt(SE/m);  
fprintf('Equation: y = %.4f + %.4fx \n',c(1),c(2));
fprintf('RMSE: %.4f \n',RMSE);
figure;
plot(x_dat, y_dat); 
grid on;
x_line = linspace(min(x_dat),max(x_dat),100);
y_line = c(1)+c(2)*x_line;
plot(x_line,y_line);