clc; clear All; close all;
x_dat = [0;1;2;5];
y_dat = [0;3;3;6];
m = length(x_dat);
A = [ones(m,1),x_dat,x_dat.^2];
b = y_dat;
M = A'*A;
N = A'*b;
c = inv(M)*N;
y_pred = A*c;
residuals =y_dat-y_pred;
RMSE_parabola = sqrt(sum(residuals.^2)/m);
fprintf('Equation: y = %.4f + %.4fx + %.4fx^2 \n',c(1),c(2),c(3));
fprintf('RMSE (Parabola): %.4f \n',RMSE_parabola);
figure;
plot(x_dat, y_dat);
grid on;
x_curve = linspace(min(x_dat),max(x_dat),100);
y_curve = c(1)+c(2)*x_curve+c(3)*x_curve.^2;
plot(x_curve,y_curve);